[package]
name = "rclite"
version = "0.1.1"
edition = "2021"
authors = ["Khashayar Fereidani"]
description = "The small reference counting solution for Rust"
repository = "https://github.com/fereidani/rclite"
documentation = "https://docs.rs/rclite"
keywords = ["arc", "rc", "no_std"]
categories = ["data-structures", "concurrency"]
license = "MIT"
readme = "README.md"