[package]
name = "rclite"
version = "0.1.3"
edition = "2018"
rust-version = "1.47"
authors = ["Khashayar Fereidani"]
description = "The small reference counting solution for Rust"
repository = "https://github.com/fereidani/rclite"
documentation = "https://docs.rs/rclite"
keywords = ["arc", "rc", "no_std"]
categories = ["data-structures", "concurrency"]
license = "MIT OR Apache-2.0"
readme = "README.md"